services:
  app:
    build: .
    environment:
      NODE_ENV: 'development'
    command: /bin/sh -c "npm run dev"
    ports:
      - 3000:4321
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
