version: '3'

services:
  app:
    build: .
    tty: true
    environment:
      NODE_ENV: 'development'
    command: /bin/sh -c "npm run dev --host 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
